import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
import 'angular-filter';

// Import our templates file (generated by Gulp)
import './config/app.templates';

// Import our app functionaity
import './article';
import './auth';
import './components';
import './home';
import './layout';
import './newtest';
import './profile';
import './services';
import './settings';




const requires = [
    'ui.router',
    'angular.filter',
    'templates',
    'app.article',
    'app.auth',
    'app.components',
    'app.home',
    'app.layout',
    'app.newtest',
    'app.profile',
    'app.services',
    'app.settings'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});